### ISSUE TITLE
CAS connector with WSO2 IS 5.3

### ISSUE THREAD

**Issue by isra-abdelsalam** [wso2-extensions/identity-inbound-auth-cas#14]
Dears , 
Greetings ,,, first i would like to appreciate your great work in the CAS connector .
i used it with WSO2 IS 5.2.0 and its working well , but when i upgrade it to 5.3.0 i faced some issues in redirection between client (my Application) and WSO2 (CAS server ) .
the error message that appears was : 
"500 internal server error "   

then i traced back the error log "wso2carbon.log" , but i can't find any type of error.
so kindly help me to make it work .
thanks in advance .

**Comment by isra-abdelsalam** [comment]
Hello 

Any Help !!!!!!

**Comment by Kanapriya** [comment]
Hi
We were able to reproduce this issue, please use the following public jira to track this.
https://wso2.org/jira/browse/ISCONNECT-68
Thanks

**Comment by Shakila** [comment]
Hi,

Please find the latest authenticator [1] which is compatible with WSO2 Identity Server 5.3.0.
https://store.wso2.com/store/assets/isconnector/details/b9c91dbd-2e87-4aae-bcfa-f6077079a44e

Thanks
