### ISSUE TITLE
Issue with CAS on wso2is 5.3, 5.6 and  5.7 "server 500 error"

### ISSUE THREAD

**Issue by malnajdi** [wso2-extensions/identity-inbound-auth-cas#29]
**Description:**
The issue is i am getting server error 500 in 2 cases.
Case 1: when the url that i want to be behind CAS is https://example.com/hello/ but i only configure CAS URL in the wso2 identity server - service provider to be https://example.com/.

Case 2: When i click on the logout i am fronted with the same error "server error 500"

ERROR {org.apache.catalina.core.StandardWrapperValve} -  Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception 
org.wso2.carbon.identity.application.authentication.framework.inbound.FrameworkRuntimeException: org.wso2.carbon.identity.application.authentication.framework.inbound.FrameworkRuntimeException: No IdentityProcessor found to process the request

**Suggested Labels:**
issue, 2.0.2, improvement
 
**Suggested Assignees:**
@Shakila @Kanapriya 

**Affected Product Version:**
2.0.1, 2.0.2, wso2is-5.3.0, wso2is-5.6.0, wso2is-5.7.0

**OS, DB, other environment details and versions:**    
Linux - Debian, Postgresql

**Steps to reproduce:**
I followed this guide https://docs.wso2.com/display/ISCONNECTORS/Configuring+CAS+Inbound+Authenticator
when i do any of the described issue on the top it breaks.

**Related Issues:**
https://github.com/wso2/product-is/issues/3861

**Comment by SpaceCoyotte** [comment]
Having the issue here... Does anybody have an idea, fix or workaround?

**Comment by malnajdi** [comment]
@SpaceCoyotte I was told to make another issue there and i did. https://github.com/wso2/product-is/issues/4610

**Comment by ten2net** [comment]
I have encountered the same problem. I am using as-client-core-3.2.1

**Comment by SpaceCoyotte** [comment]
@mohdnajdy Thank you. I'll follow on [wso2/product-is#4610](wso2/product-is#4610) from now... This one can be closed, I guess.

**Comment by malnajdi** [comment]
closed, related to https://github.com/wso2-extensions/identity-inbound-auth-cas/issues/wso2/product-is#4610

**Comment by ajanthan** [comment]
I am facing this issue with IS 5.9.0. I've patched the cas connector with code from @janakamarasena's fork. Still it did not work. Any help?
